### ISSUE TITLE
Calendar

### ISSUE THREAD

**Issue by EricksonVIK** [EricksonVIK/Personal_Sunrise_NC#4]
- FullCalendar with plugins
- MongoDB connection
- Controller: Event
- Model: Event
- Integrate for display

**Comment by AaronMikelKey** [comment]
Event calendar connects to DB and displays events.

**STILL NEEDED: ** 

Add ability to 'request events' from normal users

Add ability to set events by owner

**Comment by AaronMikelKey** [comment]
Closing since request works.  Will open another issue for owner approving events.
